<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>8cae9f02-6967-4b5b-b6d2-ed454ecd66dc</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Quantora.Application\Quantora.Application.csproj" />
    <ProjectReference Include="..\Quantora.Contracts\Quantora.Contracts.csproj" />
    <ProjectReference Include="..\Quantora.Infrastructure\Quantora.Infrastructure.csproj" />
    <ProjectReference Include="..\Quantora.Shared\Quantora.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Middlewares\" />
    <Folder Include="swagger\" />
  </ItemGroup>

</Project>
